# Generated by Django 5.1.6 on 2025-02-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_area', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_subArea', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_instalación', models.DateField()),
                ('fecha_updated', models.DateField(auto_now=True)),
                ('descripción', models.TextField()),
                ('disponibilidad', models.CharField(choices=[('ON', 'EN OPERACIÓN'), ('BK', 'EN RESERVA/MANTENIMIENTO'), ('OFF', 'FUERA DE OPERACIÓN PERMANENTE')], max_length=3)),
                ('fotografía', models.CharField(max_length=130, null=True)),
                ('link', models.CharField(max_length=130, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.area')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_parte', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=130)),
                ('descripción', models.TextField()),
                ('fotografía', models.CharField(max_length=130)),
                ('anexo', models.CharField(max_length=130)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.maquina')),
            ],
        ),
    ]
