# Generated by Django 5.1.6 on 2025-02-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_subarea_subarea_alter_maquina_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='fotografía',
        ),
        migrations.AddField(
            model_name='maquina',
            name='foto',
            field=models.ImageField(default=0, upload_to='images_maquinas'),
            preserve_default=False,
        ),
    ]
