# Generated by Django 5.1.6 on 2025-02-23 02:16

import activos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_remove_maquina_fotografía_maquina_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='foto',
            field=models.ImageField(default='Por defecto.png', upload_to=activos.models.Maquina.wrapper),
        ),
    ]
