# Generated by Django 5.1.6 on 2025-02-23 03:52

import activos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_alter_maquina_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='link',
            field=models.FileField(default=0, upload_to=activos.models.Maquina.inner),
            preserve_default=False,
        ),
    ]
