# Generated by Django 5.1.6 on 2025-03-12 01:24

import activos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_alter_maquina_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mantenimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('fecha_planificada', models.DateField()),
                ('fecha_ejecutada', models.DateField(auto_now=True)),
                ('atraso', models.BooleanField(default=False)),
                ('evidencia', models.FileField(upload_to=activos.models.mantenimientos.inner)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.maquina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
