# Generated by Django 5.1.6 on 2025-03-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_mantenimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientos',
            name='fecha_ejecutada',
            field=models.DateField(null=True),
        ),
    ]
