# Generated by Django 5.1.6 on 2025-03-12 04:58

import activos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_alter_mantenimientos_fecha_ejecutada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientos',
            name='estado',
            field=models.CharField(choices=[('PRE', 'PREVENTIVO'), ('CORR', 'CORRECTIVO'), ('DIC', 'PREDICTIVO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='mantenimientos',
            name='evidencia',
            field=models.FileField(null=True, upload_to=activos.models.mantenimientos.inner),
        ),
    ]
