# Generated by Django 5.1.6 on 2025-03-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_alter_mantenimientos_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimientos',
            name='estado',
        ),
        migrations.AddField(
            model_name='mantenimientos',
            name='estado_ejecucion',
            field=models.CharField(choices=[('SI', 'EJECUTADA'), ('NO', 'NO EJECUTADA')], default='NO', max_length=5),
        ),
        migrations.AlterField(
            model_name='mantenimientos',
            name='tipo',
            field=models.CharField(choices=[('PRE', 'PREVENTIVO'), ('CORR', 'CORRECTIVO'), ('DIC', 'PREDICTIVO')], max_length=5),
        ),
    ]
