# Generated by Django 5.1.6 on 2025-03-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_remove_mantenimientos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarea',
            name='cod_subArea',
            field=models.CharField(max_length=15),
        ),
    ]
