# Generated by Django 5.1.6 on 2025-03-16 12:48

import activos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_alter_subarea_cod_subarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientos',
            name='evidencia',
            field=models.FileField(upload_to=activos.models.mantenimientos.inner),
        ),
    ]
