# Generated by Django 5.1.6 on 2025-03-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_alter_mantenimientos_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientos',
            name='evidencia',
            field=models.FileField(upload_to='acividades/'),
        ),
    ]
