# Generated by Django 5.1.6 on 2025-03-26 03:52

import activos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0012_alter_mantenimientos_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimientos',
            name='atraso',
        ),
        migrations.RemoveField(
            model_name='mantenimientos',
            name='estado_ejecucion',
        ),
        migrations.AlterField(
            model_name='mantenimientos',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=activos.models.mantenimientos.inner),
        ),
        migrations.AlterField(
            model_name='mantenimientos',
            name='fecha_ejecutada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
