# Generated by Django 5.1.6 on 2025-03-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0013_remove_mantenimientos_atraso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimientos',
            old_name='user',
            new_name='responsable',
        ),
    ]
