# Generated by Django 5.1.6 on 2025-03-28 21:32

import activos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0014_rename_user_mantenimientos_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=activos.models.Maquina.wrapper),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to=activos.models.Maquina.inner),
        ),
    ]
