# Generated by Django 5.1.6 on 2025-03-29 04:45

import activos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0015_alter_maquina_foto_alter_maquina_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='parte',
            name='fotografía',
        ),
        migrations.AddField(
            model_name='parte',
            name='anexo1',
            field=models.ImageField(blank=True, null=True, upload_to=activos.models.Parte.inner),
        ),
        migrations.AddField(
            model_name='parte',
            name='anexo2',
            field=models.FileField(blank=True, null=True, upload_to=activos.models.Parte.inner),
        ),
    ]
