# Generated by Django 5.1.6 on 2025-03-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0016_remove_parte_anexo_remove_parte_fotografía_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='mantenimiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
