# Generated by Django 5.1.6 on 2025-03-30 03:42

import activos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0017_parte_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='anexo1',
            field=models.FileField(blank=True, null=True, upload_to=activos.models.Parte.inner),
        ),
    ]
